name: gh-agt-01
on: 
  repository_dispatch:
    types: [gh-agt-01]
jobs:
  gh-agt-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup jks agent
        uses: ./.github/cust-actions/setup-jks-agt 
