name: gh-agt-02
on: 
  repository_dispatch:
    types: [gh-agt-02]
jobs:
  gh-agt-02:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup jks agent
        uses: ./.github/cust-actions/setup-jks-agt 
        with:
          SSH_KEY_FOR_GITEE: ${{ secrets.SSH_KEY_FOR_GITEE }}
          ALIYUN_MAVEN_USERNAME: ${{ secrets.ALIYUN_MAVEN_USERNAME }}
          ALIYUN_MAVEN_PASSWORD: ${{ secrets.ALIYUN_MAVEN_PASSWORD }}
          appConfig: ${{ github.event.client_payload.appConfig }}
          agtDownloadURL: ${{ github.event.client_payload.agt.downloadURL }}
          agtWorkdir: ${{ github.event.client_payload.agt.workdir }}
          agtURL: ${{ github.event.client_payload.agt.URL }}
          agtKey: ${{ github.event.client_payload.agt.key }}
          keepalive: ${{ github.event.keepalive }}
