name: gh-agt-01
on: 
  repository_dispatch:
    types: [gh-agt-01]
jobs:
  gh-agt-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
          
      # - name: Install Squid
      #   run: |
      #    sudo apt update
      #    sudo apt install -y squid
      #    sudo sed -i 's/http_access deny all/http_access allow all/g' /etc/squid/squid.conf
      #    grep port /etc/squid/squid.conf
      #    sudo systemctl restart squid
      #    sudo systemctl status squid
      
      # - name: Install frpc
      #   run: |
      #     wget https://github.com/fatedier/frp/releases/download/v0.42.0/frp_0.42.0_linux_amd64.tar.gz
      #     tar xf frp_0.42.0_linux_amd64.tar.gz
      #     sudo cp frp_0.42.0_linux_amd64/frpc /usr/bin/
      #     sudo cp frp_0.42.0_linux_amd64/systemd/frpc.service /etc/systemd/system/
      #     sudo mkdir /etc/frp
      #     cat > frpc.ini <<EOF
      #       [common]
      #       server_addr = 112.124.20.91
      #       server_port = 7000
            
      #       [squid-1]
      #       type = tcp
      #       local_ip = 127.0.0.1
      #       local_port = 3128
      #       remote_port = 7104
      #     EOF
      #     sudo mv frpc.ini /etc/frp/
      #     cat /etc/frp/frpc.ini
      #     sudo systemctl daemon-reload
      #     sudo systemctl start frpc.service
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2.0.0

      - name: Test Docker version
        run: docker --version
        
      - name: Install jenkins agent
        run: |
          wget ${{ github.event.client_payload.agt.downloadURL }}
          sudo mkdir -p /data/jenkins && sudo chown $USER: /data/jenkins
          java -jar agent.jar -jnlpUrl ${{ github.event.client_payload.agt.URL }} -secret "::add-mask::${{ github.event.client_payload.agt.key }}" -workDir "${{ github.event.client_payload.agt.workdir }}"
          
      - name: Don't kill instace
        run: sleep ${{ github.event.client_payload.keepalive }}
