name: gh-agt-01
on: 
  repository_dispatch:
    types: [gh-agt-01]
jobs:
  gh-agt-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup jks agent
        uses: ./.github/cust-actions/setup-jks-agt 
        with:
          SSH_KEY_FOR_GITEE: ${{ secrets.SSH_KEY_FOR_GITEE }}
          ALIYUN_MAVEN_USERNAME: ${{ secrets.ALIYUN_MAVEN_USERNAME }}
          ALIYUN_MAVEN_PASSWORD: ${{ secrets.ALIYUN_MAVEN_PASSWORD }}
          client_payload: ${{ github.event.client_payload }}
