name: gh-agt-01
on: 
  repository_dispatch:
    types: [gh-agt-01]
jobs:
  gh-agt-01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2.0.0

      - name: Test Docker version
        run: docker --version

      - name: Prepare Dependency
        run: |
          echo "${{ secrets.SSH_KEY_FOR_GITEE }}" > id_rsa && chmod 600 id_rsa
          conf=`echo ${{ github.event.client_payload.appConfig }} | base64 --decode`
          for repo in `echo $conf | jq -r '.[] | .repoName' | sort | uniq`
          do
            ls -la id_rsa && md5sum id_rsa
            [ ! -d "$repo" ] && GIT_SSH_COMMAND='ssh -i id_rsa -o StrictHostKeyChecking=no' git clone git@gitee.com:primtal/$repo.git
            for app in `echo $conf | jq -c ".[] | select(.repoName | contains(\"$repo\"))"`
            do
              appType=`echo $app | jq -r '.appType'`
              if [ $appType == "Backend" ]; then
                docker run -i -v "$repo":/usr/src/mymaven -v "$HOME/.m2":/root/.m2 -w /usr/src/mymaven vnnvanhuong/maven-oracle-jdk:8 mvn dependency:get
              elif [ $appType == "Frontend" ]; then
                docker run -i -v "$repo":/usr/src/mynode -v "$HOME/node_modules":/root/node_modules -w /usr/src/mynode --env NODE_PATH=/root/node_modules node:10.16.0 sh -c "npm set unsafe-perm true && npm install"
              else
                echo "unsupported appType!"
              fi
            done
          done

      - name: Install jenkins agent
        run: |
          wget ${{ github.event.client_payload.agt.downloadURL }}
          sudo mkdir -p /data/jenkins && sudo chown $USER: /data/jenkins
          java -jar agent.jar -jnlpUrl ${{ github.event.client_payload.agt.URL }} -secret "${{ github.event.client_payload.agt.key }}" -workDir "${{ github.event.client_payload.agt.workdir }}"
          
      - name: Don't kill instace
        run: sleep ${{ github.event.client_payload.keepalive }}
