name: onlyoffice
on: 
  repository_dispatch:
    types: [onlyoffice]
jobs:
  onlyoffice:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - uses: actions/checkout@v2

      - name: Change runner password
        run: |
          echo -e "runner\nrunner" | sudo passwd runner

      - name: Install frpc
        run: |
          wget https://github.com/fatedier/frp/releases/download/v0.42.0/frp_0.42.0_linux_amd64.tar.gz
          tar xf frp_0.42.0_linux_amd64.tar.gz && rm -rf frp_0.42.0_linux_amd64.tar.gz
          sudo cp frp_0.42.0_linux_amd64/frpc /usr/bin/
          sudo cp frp_0.42.0_linux_amd64/systemd/frpc.service /etc/systemd/system/
          sudo mkdir /etc/frp
          cat > frpc.ini <<EOF
            [common]
            server_addr = 112.124.20.91
            server_port = 7000

            [ssh2-1]
            type = tcp
            local_ip = 127.0.0.1
            local_port = 22
            remote_port = 7103
          EOF
          sudo mv frpc.ini /etc/frp/
          cat /etc/frp/frpc.ini
          sudo systemctl daemon-reload
          sudo systemctl start frpc.service
      
      - name: Don't kill instace
        run: tail -f /var/log/auth.log